Fix flaky TestCoProcessReload test
Especially when run with -count N, it would sometimes fail with:

	--- FAIL: TestCoProcessDispatchEvent (0.01s)
		coprocess_test.go:73: Wrong event metadata

This is because another test was firing an event that it wasn't cleaning
up. Throw it away to not get other tests to receive the wrong event.